name = "chat"
main = "src/worker/index.ts"
compatibility_date = "2022-05-03"
node_compat = true
#
#[site]
#bucket = "dist"

[[kv_namespaces]]
binding = "DATABASE"
id = ""

[vars]
IS_PROD = true
USER_ID_START = "623415"
USER_ID_CHATGPT = "10001"
# 24H
TOKEN_EXPIRE_TIME_SEC = 86400000
JWT_SECRET = ""
GITHUB_CLIENT_ID = ""
GITHUB_CLIENT_SECRET = ""

GOOGLE_REDIRECT_PROD_URL="https://xxxx.dev/auth/google/callback"
GOOGLE_CLIENT_ID = ""
GOOGLE_CLIENT_SECRET = ""

FRONTEND_AUTH_CALLBACK_URL = "https://xxxx.dev"
OPENAI_API_KEY=""
